//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalAJSR.Models.ConectDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAtencionCliente
    {
        public int IdCliente { get; set; }
        public int IdTipoAtencion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbTipoAtencion tbTipoAtencion { get; set; }
    }
}
